# Generated by Django 4.2.6 on 2023-12-08 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('DeptNo', models.IntegerField(primary_key=True, serialize=False)),
                ('DName', models.CharField(max_length=50)),
                ('Loc', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Salgrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Grade', models.IntegerField()),
                ('Losal', models.PositiveIntegerField()),
                ('Hisal', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('EmpNo', models.IntegerField(primary_key=True, serialize=False)),
                ('EName', models.CharField(max_length=30)),
                ('Job', models.CharField(max_length=15)),
                ('Mgr', models.IntegerField()),
                ('Hiredate', models.DateField()),
                ('Sal', models.PositiveIntegerField()),
                ('Commision', models.IntegerField()),
                ('DeptNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.dept')),
            ],
        ),
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bamount', models.PositiveIntegerField()),
                ('Empno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.emp')),
            ],
        ),
    ]
